### ISSUE TITLE
Feature request: full-date format

### ISSUE THREAD

**Issue by outer-circle** [swaggest/php-json-schema#106]
I just started to experiment with this great library - thanks! - I created PHP classes from an existing JSON schema. The schema contains 

 "birthDate": {
          "type": "string",
          "format": "full-date",
          "description": "JJJJ-MM-TT"
        }

but there is no validation of this format in the php-json-schema library.
I am aware of the fact that as of present the format "full-date" is the same as "date". But "full-date" is included in the Schema draft V7:

https://tools.ietf.org/html/draft-handrews-json-schema-validation-01

It would be great if you could add this format option to the Format::class.

**Comment by vearutop** [comment]
Done, `v0.12.30` tagged.

**Comment by outer-circle** [comment]
Wow - done with lightning speed! Thank you!
