### ISSUE TITLE
Can I infer json schema ?

### ISSUE THREAD

**Issue by ilazaridis** [swaggest/php-json-schema#110]
Is there a way to do that out of json sample or in any other way that I couldn't find yet ?

Thanks

**Comment by vearutop** [comment]
You can try https://github.com/swaggest/json-schema-maker (https://github.com/swaggest/json-cli#buildschema).

https://app.quicktype.io this tool also can make schema from JSON sample.

**Comment by ilazaridis** [comment]
Thanks, although I expected that this would be possible once you implement `public static function setUpProperties($properties, Schema $ownerSchema)`

**Comment by vearutop** [comment]
Yes, it is also possible to export schema of a class that implements `setupProperties`.
```php
        $schema = MyClass::schema();
        $schemaData = Schema::export($schema);
```
See [test] (https://github.com/swaggest/php-json-schema/blob/v0.12.31/tests/src/PHPUnit/ClassStructure/ExportSchemaTest.php#L16-L35) for example.

**Comment by ilazaridis** [comment]
Awesome, thank you!

That's what I was looking for.
