### ISSUE TITLE
Unterminated Quoted String

### ISSUE THREAD

**Issue by braandl** [swaggest/php-json-schema#118]
When trying to generate a JSON-Schema from a JSON String that contains single-quotes inside of strings, 
the Lib states:

`syntax error: unterminated quoted string`

but the JSON input looks valid to me, and can also be transferred to browsers etc.

Example for a failing JSON definition:
```json
{
    "myString": "This is 'an interesting' string"
}
```

**Comment by vearutop** [comment]
Hi, could you share some code to reproduce your issue?

**Comment by braandl** [comment]
Oh, this is very supid, and I am very sorry, but I did mistake the library. The issue is from `quicktype` not `php-json-schema` I just misread a namespace. Sorry for the inconvenience.

**Comment by vearutop** [comment]
No worries, thank you for checking.
