### ISSUE TITLE
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.1.0"

### ISSUE THREAD

**Issue by massadm** [swaggest/php-json-schema#135]
Just `composer require "swaggest/json-schema"` for new project and got %subj%.

Looked at what changed https://github.com/swaggest/php-json-schema/compare/v0.12.38...v0.12.39 and found out that added "Polyfill dependency for mbstring extension".

Do these directives in the `package.json` reflect your true intent?
```
  "require": {
    "symfony/polyfill-mbstring": "^1.19"
  },
  "suggest": {
    "ext-mbstring": "For better performance"
  }
```

I'm asking because the requirements have changed significantly with introduction of `symfony/polyfill-mbstring` package.
```
        {
            "name": "symfony/polyfill-mbstring",
            "version": "v1.23.1",

            "require": {
                "php": ">=7.1"
            },
```

Thanks!

**Comment by exerror8** [comment]
[[Solved] Composer detected issues in your platform: Your Composer dependencies require a PHP version ](https://exerror.com/composer-detected-issues-in-your-platform-your-composer-dependencies-require-a-php-version/)
