### ISSUE TITLE
GOTO operator in PHP, really?

### ISSUE THREAD

**Issue by christian-weiss** [swaggest/php-json-schema#142]
https://github.com/swaggest/php-json-schema/blob/0dbf9e7857d065bde50605972933d6c38dbe6b8c/src/Schema.php#L1186

I just spotted this in your code base on the very first look, while i was evaluating if i should use your lib...

**Comment by vearutop** [comment]
I'm not sure I understand the issue. Do you mind elaborating it a bit?

**Comment by christian-weiss** [comment]
This image is from the official PHP manual:
[<img alt="alt_text" src="https://www.php.net/manual/de/images/0baa1b9fae6aec55bbb73037f3016001-xkcd-goto.png" />]
...i think a "goto" operator is a code smell, so it indicates that the architecture of this code base is suboptimal designed. 

Please consider to split that method (X):
1. move first part of X  into a separate method (A)
2. move second part of X into another separate method (B)
3. call A and B from X (method X is now very small)
4. replace "goto" in A by a "return" statement 

Use class members to pass data around if necessary (increase coherence of that class). 
This small refactoring is just following the boy scout rule - there is more to be done...

I recommend to read the book "Clean Code".

**Comment by vearutop** [comment]
I have the opposite opinion, thank you.
