### ISSUE TITLE
Handle Enum as array

### ISSUE THREAD

**Issue by kranack** [swaggest/php-json-schema#30]
I use your library since, well... a few hours and I have to say it's great.
I just have a problem with my schema validation, I described it with a property which can be an _array_ or a _integer_ like this

`"inputStates": { "type": ["string", "array"] }`

The schema import is doing well but when I'm trying to parse my JSON data, I get this exception

`PHP Swaggest\\JsonSchema\\Exception\\EnumException:  Enum failed, enum: ["array","boolean","integer","null","number","object","string"], data: ["string","array"] at #->properties:definitions->additionalProperties:command->properties:properties->additionalProperties:inputStates->properties:type->anyOf[0]`

I don't know if this is a real issue or just me misunderstanding the library but it should be great if the processEnum function handles the array.

Tell me what you think about it :)

**Comment by vearutop** [comment]
Hello, could you share an example of schema and data that are causing problems? 
Maybe you've got a typo somewhere :)

> an array or a integer 

is not same as

> `"type": ["string", "array"]`

If you want to allow array or integer you need `"type": ["integer", "array"]`.

I've tried with
```
[
  {
    "description": "Multi-type",
    "schema": {
      "type": "object",
      "properties": {
        "inputStates": {"type": ["string", "array"]}
      }
    },
    "tests": [
      {"description": "valid with string", "data": {"inputStates": "abc"}, "valid": true},
      {"description": "still valid with array", "data": {"inputStates": ["abc", "def"]}, "valid": true},
      {"description": "invalid with int", "data": {"inputStates": 23}, "valid": false}
    ]
  }
]
```
It works as expected with `v0.11.0`.

**Comment by kranack** [comment]
Thanks for the reply :)

In fact, I mixed up my types in my previous message : I expect an _array of intege_r or a _string_.
This is the part of my schema not working as expected

```
"command": {
    "type": "object",
    "properties": {
        "label": { "type": "string"	},
        "cmd": { "type": "string" },
        "inputStates": {
            "type": ["string", "array"],
            "uniqueItems": true,
            "maxLength": 1,
            "pattern": "^\\*$",
            "items": { "type": "integer" }
        },
        "outputState": { "type": "integer" },
        "rights": {
            "type": ["string", "array"],
            "uniqueItems": true,
            "maxLength": 1,
            "pattern": "^\\*$",
            "items": { "type": "integer" }
        },
        "params": {
            "type": "object",
            "minProperties": 1
        }
    },
    "additionalProperties": false,
    "required": ["label", "cmd", "inputStates", "outputState"]
}
```

Which not work with those data

```
{"label": "reset",		"cmd": "default.reset",				"inputStates": [0,1,2,3], "outputState": 0, "rights":[2]}
```

```
{"label": "reset",		"cmd": "default.reset",				"inputStates": "*", "outputState": 0, "rights":[2]}
```

I'm also working with the `v.0.11.0`

**Comment by vearutop** [comment]
Your schema and data are correct and pass validation ([test](https://github.com/swaggest/php-json-schema/blob/fa4f16c64adedf3d9ea174fa346d158089a5200f/tests/resources/suite/issue-30.json), [travis build](https://travis-ci.org/swaggest/php-json-schema/builds/365611640)).

So it must be something else needed to reproduce the problem. Schema implementation does allow array of types. 

https://github.com/swaggest/php-json-schema/blob/master/src/JsonSchema.php#L256
This is `type` property definition, it has two schemas in `anyOf`: `enum` value and `array` of `enum`-ed items.

**Comment by kranack** [comment]
Ok, so it a problem with the implementation of the Schema.php ?
I just saw that you have a _TODO_ to support complex structures on https://github.com/swaggest/php-json-schema/blob/master/src/Schema.php#L225

**Comment by kranack** [comment]
Oh ok! 

I attach here a zip where you can find the complete schema and a minimal set of data to test it. I'm not sure but maybe my usage of "definitions" is not correct in my usage.

Tell me what you think about it
[Workflow-#30.zip](https://github.com/swaggest/php-json-schema/files/1903785/Workflow-.30.zip)

**Comment by vearutop** [comment]
This script worked for me without error  ¯\_(ツ)_/¯
```
<pre>C:\data\dev\php-json-schema\Workflow-.30\script.php:19:
class Swaggest\JsonSchema\Structure\ObjectItem#199 (7) {
  protected $__nestedObjects =>
  NULL
  protected $__documentPath =>
  string(1) "#"
  protected $__fromRef =>
  NULL
  protected $__additionalPropertyNames =>
  NULL
  protected $__patternPropertyNames =>
  NULL
  protected $__arrayOfData =>
  array(4) {
    'name' =>
    string(11) "My Workflow"
    'rsrc' =>
    array(1) {
      [0] =>
      class Swaggest\JsonSchema\Structure\ObjectItem#192 (7) {
        ...
      }
    }
    'states' =>
    array(5) {
      [0] =>
      class Swaggest\JsonSchema\Structure\ObjectItem#185 (7) {
        ...
      }
      [1] =>
      class Swaggest\JsonSchema\Structure\ObjectItem#175 (7) {
        ...
      }
      [2] =>
      class Swaggest\JsonSchema\Structure\ObjectItem#161 (7) {
        ...
      }
      [3] =>
      class Swaggest\JsonSchema\Structure\ObjectItem#198 (7) {
        ...
      }
      [4] =>
      class Swaggest\JsonSchema\Structure\ObjectItem#206 (7) {
        ...
      }
    }
    'apps' =>
    array(3) {
      [0] =>
      class Swaggest\JsonSchema\Structure\ObjectItem#208 (7) {
        ...
      }
      [1] =>
      class Swaggest\JsonSchema\Structure\ObjectItem#210 (7) {
        ...
      }
      [2] =>
      class Swaggest\JsonSchema\Structure\ObjectItem#212 (7) {
        ...
      }
    }
  }
  private $iterator =>
  NULL
}
</pre>
```

**Comment by kranack** [comment]
Me neither but when I launch it with apache I get some `EnumException`. I don't know why it's working with php-cli but not with apache :/

**Comment by vearutop** [comment]
Your original exception looks very weird, for bad schema:
```json
{"type":["string","array","unknown"]}
```

 it should be multiline like this:
```
No valid results for anyOf {
  0: Enum failed, enum: ["array","boolean","integer","null","number","object","string"], data: ["string","array","unknown"] at #->properties:properties->additionalProperties:inputStates->properties:type->anyOf[0]
  1: Enum failed, enum: ["array","boolean","integer","null","number","object","string"], data: "unknown" at #->properties:properties->additionalProperties:inputStates->properties:type->anyOf[1]->items[2]:2
} at #->properties:properties->additionalProperties:inputStates->properties:type
```

Because `type` is defined as two items of `anyOf`, both are checked and the schema is invalid only when both rules are violated. The resulting error message shows errors for all involved in `anyOf` rules.

**Comment by kranack** [comment]
I don't see the "unknown" type in my exception but yes, it looks very weird. The thing is these exceptions appear as **notice** in my apache _error.log file_.

Okay, so this exception should only be thrown if none of my type matched but in the mystical world of apache, there's a way it's thrown even if it's not the case? 🌝

**Comment by vearutop** [comment]
It seems that your env logs exception that is already caught by PHP code. To me that behaviour is wrong, and I'm unable to reproduce. 

Can you share details on your environment: apache version, mode (mod_php or fastcgi or cgi), php version, non-standard php extensions, php framework if used?

**Comment by kranack** [comment]
Ok, sure.

**PHP**

_Version_
```
PHP 7.1.12 (cli) (built: Nov 29 2017 11:12:48) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

_Modules_
```
[PHP Modules]
ast
bcmath
bz2
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
hash
igbinary
imagick
json
ldap
libxml
mbstring
memcached
mongodb
mysqlnd
OAuth
openssl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
xdebug
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]
Xdebug
```

_Framework_
None

**Apache**

_Version_
```
Server version: Apache/2.4.29 (Unix)
Server built:   Jan  8 2018 16:45:28
Server's Module Magic Number: 20120211:68
Server loaded:  APR 1.6.3, APR-UTIL 1.6.1
Compiled using: APR 1.6.3, APR-UTIL 1.6.1
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/opt/local"
 -D SUEXEC_BIN="/opt/local/bin/suexec"
 -D DEFAULT_PIDLOG="var/run/apache2/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="etc/apache2/mime.types"
 -D SERVER_CONFIG_FILE="etc/apache2/httpd.conf"
```

_Modules_

```
Loaded Modules:
 core_module (static)
 so_module (static)
 http_module (static)
 mpm_prefork_module (static)
 authn_file_module (shared)
 authn_core_module (shared)
 authz_host_module (shared)
 authz_groupfile_module (shared)
 authz_user_module (shared)
 authz_core_module (shared)
 authnz_ldap_module (shared)
 access_compat_module (shared)
 auth_basic_module (shared)
 allowmethods_module (shared)
 file_cache_module (shared)
 cache_module (shared)
 cache_disk_module (shared)
 cache_socache_module (shared)
 socache_shmcb_module (shared)
 socache_dbm_module (shared)
 socache_memcache_module (shared)
 watchdog_module (shared)
 reqtimeout_module (shared)
 request_module (shared)
 include_module (shared)
 filter_module (shared)
 xml2enc_module (shared)
 proxy_html_module (shared)
 mime_module (shared)
 ldap_module (shared)
 log_config_module (shared)
 env_module (shared)
 mime_magic_module (shared)
 expires_module (shared)
 headers_module (shared)
 setenvif_module (shared)
 version_module (shared)
 proxy_module (shared)
 proxy_connect_module (shared)
 proxy_ftp_module (shared)
 proxy_http_module (shared)
 proxy_fcgi_module (shared)
 proxy_scgi_module (shared)
 proxy_wstunnel_module (shared)
 proxy_ajp_module (shared)
 proxy_balancer_module (shared)
 proxy_express_module (shared)
 proxy_hcheck_module (shared)
 session_module (shared)
 session_cookie_module (shared)
 session_dbd_module (shared)
 slotmem_shm_module (shared)
 ssl_module (shared)
 lbmethod_byrequests_module (shared)
 lbmethod_bytraffic_module (shared)
 lbmethod_bybusyness_module (shared)
 unixd_module (shared)
 status_module (shared)
 autoindex_module (shared)
 vhost_alias_module (shared)
 negotiation_module (shared)
 dir_module (shared)
 userdir_module (shared)
 alias_module (shared)
 rewrite_module (shared)
 php7_module (shared)
```

**Comment by kranack** [comment]
Were you able to reproduce the behaviour with my config ?

**Comment by vearutop** [comment]
@kranack, I was unable to reproduce your problem with apache and PHP, but I think it has nothing to with them, neither with library.
My guess, you have an issue because of xdebug being configured with `xdebug.show_exception_trace=1`.

> xdebug.show_exception_trace
> Type: integer, Default value: 0
>
> When this setting is set to 1, Xdebug will show a stack trace whenever an Exception or Error is raised - even if this Exception or Error is actually caught.
>
> Error 'exceptions' were introduced in PHP 7.
https://xdebug.org/docs/all_settings

For me, when I enable this setting I start getting:
```
PHP Swaggest\JsonSchema\Exception\EnumException:  Enum failed, enum: ["array","boolean","integer","null","number","object","string"], data: ["string","array"] at #->properties:definitions->additionalProperties:command->properties:properties->additionalProperties:inputStates->properties:type->anyOf[0] in /Volumes/H/dev/php-json-schema/src/Schema.php on line 231
PHP Stack trace:
PHP   1. {main}() /Volumes/H/dev/php-json-schema/index.php:0
PHP   2. Swaggest\JsonSchema\Schema::import() /Volumes/H/dev/php-json-schema/index.php:19
PHP   3. Swaggest\JsonSchema\Structure\ClassStructure::import() /Volumes/H/dev/php-json-schema/src/Schema.php:132
PHP   4. Swaggest\JsonSchema\Wrapper->in() /Volumes/H/dev/php-json-schema/src/Structure/ClassStructureTrait.php:54
...........
```

Please try adding to your code: 
```php
ini_set('xdebug.show_exception_trace', 0);
```
or change PHP configuration for apache.

**Comment by kranack** [comment]
Indeed, I had this line in my PHP configuration ! I'll never imagine it could be an error in my PHP conf lol

Sorry for the inconvenience, thanks a lot for your help. I hope my next issue should be really constructive :')
