### ISSUE TITLE
Cannot use local JSON file

### ISSUE THREAD

**Issue by iursevla** [swaggest/php-json-schema#46]
I'm using php-json-schema to validate the responses of my server endpoints.

I'm testing it locally and i can't seem to find a way to reference another schma with definitions. 

My endpoint schema validator has the following:
`
"tasks": { "$ref": "definitions.json#/taskDefinition"},
` 

The other file called definitions.json has the following:
```
{
  "taskDefinition": {
    "type": "array"
  }
}
```

It always returns an error:
```
file_get_contents(definitions.json): failed to open stream: No such file or directory
 /home/ralves/projects/php-project/vendor/swaggest/json-schema/src/RemoteRef/BasicFetcher.php:14
 /home/ralves/projects/php-project/vendor/swaggest/json-schema/src/RefResolver.php:195
 /home/ralves/projects/php-project/vendor/swaggest/json-schema/src/Schema.php:698
 /home/ralves/projects/php-project/vendor/swaggest/json-schema/src/Schema.php:1139
 /home/ralves/projects/php-project/vendor/swaggest/json-schema/src/Wrapper.php:46
 /home/ralves/projects/php-project/vendor/swaggest/json-schema/src/Schema.php:863
 /home/ralves/projects/php-project/vendor/swaggest/json-schema/src/Schema.php:1139
 /home/ralves/projects/php-project/vendor/swaggest/json-schema/src/Schema.php:831
 /home/ralves/projects/php-project/vendor/swaggest/json-schema/src/Schema.php:1139
 /home/ralves/projects/php-project/vendor/swaggest/json-schema/src/Schema.php:176
 /home/ralves/projects/php-project/vendor/swaggest/json-schema/src/Wrapper.php:58
 /home/ralves/projects/php-project/vendor/swaggest/json-schema/src/Structure/ClassStructureTrait.php:60
 /home/ralves/projects/php-project/vendor/swaggest/json-schema/src/Schema.php:137
 /home/ralves/projects/php-project/tests/api/AuthenticatedCest.php:77
 /home/ralves/projects/php-project/tests/api/CoreCest.php:12
 /tmp/ide-codeception.php:494
```

I tried using `id: "file://"`, and a bunch of other things but didn't found a way to make it work.

I changed the code of the `BasicFetcher.php` so that the `$url` is the absolute path of the `definitions.json `file and it worked, but clearly it's not a solution for this problem.

PS: Searching on google for similar problem got me on [this issue](https://github.com/Julian/jsonschema/issues/98) of another project

**Comment by iursevla** [comment]
@vearutop thanks for your reply.

The solution you presented works but if i want  to have multiple defintions files for each part of my application it's easier to use my current workaround (i think).
For now, I added a placeholder in the id tag and then I replace said placeholder with the path to my schemas fiolder and doing so each developer can use it's local files.

```"id": "{{SCHEMA_PATH}}/mainPage/",```

and then in my code i do:

```
jsonSchema = json_decode(file_get_contents($absoluteSchemaPath));
str_replace('{{SCHEMA_PATH}}', self::SCHEMAS_PATH, $jsonSchema->id);
return Schema::import($jsonSchema);
```
For now this works and lets everyone use their definitions without the need for validators. 

Your solution with `file:://` is the cleanest by far.

**Comment by massadm** [comment]
> Just be aware that uri in schema is an identifier first of all, not necessarily accessible with conventional protocols.

Hi! Absolutely. And give attention to "id" property which declares a base "URL" against which related $ref "URL"s are resolved.

You do not want `file://` Schemas at all. All you want is some kind of mapping between schemas and files in storage so using `Preloaded` is the way.

_BTW due to hi-load i use `SchemaFactory` and something like `\unserialize(\gzinflate(\file_get_contents($cacheFile)))` to almost instantly receive deployed `Schema` objects._

**Comment by vearutop** [comment]
tagged `0.12.2`

@massadm I agree that totally makes sense performance-wise.

**Comment by massadm** [comment]
Please note that `file://` refer to a non-local file. [RFC8089](https://tools.ietf.org/html/rfc8089#appendix-A)

**Comment by vearutop** [comment]
@massadm thanks, the main use-case is for absolute paths `/somewhere/schema.json` so it would be `file:///somewhere/schema.json` - a local file, but maybe it makes sense to ensure that `file:///` is present in uri.

**Comment by massadm** [comment]
@vearutop `file_get_contents()` fallback to `file://` for any unrecognized [protocol](http://php.net/manual/en/wrappers.php). So `file:///...` will be used in any case to accessing local filesystem.

**Comment by vearutop** [comment]
@massadm oh, indeed, I didn't even think that `file://` was already supported out of PHP box. :)
