### ISSUE TITLE
InvalidValue error in inspect()

### ISSUE THREAD

**Issue by franksl** [swaggest/php-json-schema#52]
Hello,
With a complex schema I encountered a problem when calling the inspect() method on a LogicException object.
The error is:

Invalid argument supplied for foreach()
at line 35 of InvalidValue.php

I suppose a check for the existence as iterable of $this->subErrors should do the job.
Thanks,
Frank

**Comment by vearutop** [comment]
Thanks, fixed in `v0.12.4`.
