### ISSUE TITLE
How can i filter data with php-json-schema

### ISSUE THREAD

**Issue by jediliang** [swaggest/php-json-schema#62]
for examle 
json data:
```
{
"name":"jedi", 
"addr":"xxxxxxxx", 
"phone":"1122330"
}
```
json-schema data: 
``` 
{
    "type": "object",
    "properties": {
        "name": {
            "type":"string",
        },
        "addr": {
            "type":"string"
        }
    },
    "required": ["name","addr"]
}
```

after validate the data , i want to get  the data  
```
{
"name":"jedi", 
"addr":"xxxxxxxx"
}
```

**Comment by vearutop** [comment]
There is no such feature.

**Comment by woodongwong** [comment]
> There is no such feature.

Are you considering adding this feature?

**Comment by vearutop** [comment]
@woodongwong could you elaborate your use case (what problem is to be solved, what is expected usage scenario)? So that we can come up with a relevant solution.

**Comment by woodongwong** [comment]
@vearutop  thanks, I don't know enough about json-schema, I have found a solution.

**Comment by vearutop** [comment]
Closing as it is not clear what could/should be the filtering criteria.

**Comment by dflourusso** [comment]
> @vearutop thanks, I don't know enough about json-schema, I have found a solution.

Which solution are you using?

**Comment by vearutop** [comment]
@dflourusso can you explain your case in more detail?

**Comment by dflourusso** [comment]
> @dflourusso can you explain your case in more detail?

You said above, "I have found a solution", which solution?

**Comment by vearutop** [comment]
@dflourusso that wasn't me, @woodongwong said.

I could not come up with any solution, because I don't have full understanding of the issue and expectations.

**Comment by dflourusso** [comment]
Sorry, I got confused

Em qui., 21 de jan. de 2021 às 11:11, Viacheslav Poturaev <
notifications@github.com> escreveu:

**Comment by woodongwong** [comment]
@dflourusso I did not go through the technical means to solve this problem, but changed the business logic. However, I found this(https://github.com/uber/json-schema-filter) and hope it will help.

**Comment by vearutop** [comment]
The problem with such feature is that it is not immediately apparent what should act as removal criteria. JSON schema can describe object properties in a variety of constraints, e.g. `properties`, `propertyNames`, `patternProperties`, `additionalProperties`, etc. Properties can also participate in complex logical expressions:
```json
{"allOf":[{"properties":{"good":true}}], "not":{"required":["bad"]}}
```

Something that may be close to describe desired behavior is [`unevaluatedProperties`](https://json-schema.org/draft/2019-09/json-schema-core.html#unevaluatedProperties).

**Comment by woodongwong** [comment]
I think the topic of this issue is about `filter`, not `validate`, which is not the feature of json-schema.

**Comment by vearutop** [comment]
Sure, but this `filter` somehow uses the schema to remove properties from the original data. So the question is: having `schema` and `data` how does the `filter` decide which properties to keep and which to remove?

**Comment by woodongwong** [comment]
> Sure, but this `filter` somehow uses the schema to remove properties from the original data. So the question is: having `schema` and `data` how does the `filter` decide which properties to keep and which to remove?

According to `properties`, only the properties defined in `properties` are retained, which is very simple and crude, but very useful in some scenarios.

**Comment by vearutop** [comment]
Does it mean that schema would not have `patternProperties`, `additionalProperties` or any combinations of `allOf`/`anyOf`/`oneOf` that refer or contain properties?  Or would the filter ignore any properties mentions except of `properties` constraint at root level of schema?
