### ISSUE TITLE
Improve the support of regular expressions

### ISSUE THREAD

**Issue by vscapital** [swaggest/php-json-schema#71]
Добрый день.

При использовании ```^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$```, для проверки email строки, получаю ошибку _Swaggest\JsonSchema\Exception\StringException : Invalid regex_

Причина кроется в том, что в реализации используются разделители, которые присутствуют в регулярном выражении: https://github.com/swaggest/php-json-schema/blob/master/src/Constraint/Format.php#L113, https://github.com/swaggest/php-json-schema/blob/master/src/Helper.php#L15

Решением может быть использование ["Asymmetric delimiters"](http://codelegance.com/ideal-regex-delimiters-in-php/).

Итого 2 варианта для данного случая:
1. Править код. В двух вышеупомянутых местах использовать "asymmetric delimiters". 
2. Мы выбрали для себя на данном этапе. В регулярном выражении `\/` заменить на `\x2F`

Хорошо было бы добавить поддержку в самой библиотеке такого regex.
Сам regex взят [здесь](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email#Validation)

Спасибо.

**Comment by vearutop** [comment]
Спасибо за предложенное решение, применено в [v0.12.8](https://github.com/swaggest/php-json-schema/releases/tag/v0.12.8).
