### ISSUE TITLE
Any way to get meta by SchemaPointer?

### ISSUE THREAD

**Issue by gigi** [swaggest/php-json-schema#73]
Hi!

Is it possible to get metadata of field by `InvalidValue` exception?
For example I want to know if failed field marked as required in the schema.

```php
 try {
    $schema = Schema::import($schemaFile);         
    $schema->in((object)$data);
} catch (Exception $exception) {
    // something like this JsonPointer::get((object)$schema, $exception->getSchemaPointer())->required;        
    // or
    // $meta = $schema->getByPointer(Schema$exception->getSchemaPointer())->required;
}
```

Thanx!

**Comment by vearutop** [comment]
@gigi please see the attached commit for failed schema resolution example:
```
$failedSchemaData = JsonPointer::getByPointer($schemaData, $exception->getSchemaPointer());
```
Hope it is helpful, error inspection is also discussed in https://github.com/swaggest/php-json-schema/issues/55 and https://github.com/json-schema-org/json-schema-spec/issues/643. With JSON Schema [draft-08](https://github.com/json-schema-org/json-schema-spec/milestone/6) out error inspection in this library will likely need some revamping.

**Comment by gigi** [comment]
Not working at all.

```php
$file = __DIR__ . '/../../../vendor/development-contract/mylib/user-profile.json';

$str = '{"user":{"id":"111","is_dev":true}, ... other data}'; // my data

$schema = Schema::import($file);

try {
    $schema->in((object)json_decode($str));
} catch (Exception $e) {
    $data = json_decode(file_get_contents($file));
    $pointer = $e->getSchemaPointer();
    // /srv/www/namespace/module/test/Unit/Validator/../../..//vendor/development-contract/mylib/user-server-event.json/allOf/1/properties/authentication_provider/properties/email
    // Different errors depending on error Swaggest\JsonDiff\Exception : Key not found: srv
    // Swaggest\JsonDiff\Exception : Path must start with "/": ./user-event.json if there is ref to anither schema
   // etc
    $meta = JsonPointer::getByPointer($data, $pointer);
}
```

 I have to make a lot of string manipulations in order to get cause field
smth like this
```php
private function isRequired($schema, $schemaPointer, $dataPointer)
{
        $path = str_replace($schema->getFromRefs()[0], '', $schemaPointer);
        $pathItems = array_slice(JsonPointer::splitPath($path), 0);
        array_splice($pathItems, -2);
        $pathItems[] = 'required';
        // FIXME to much json operations
        $items = JsonPointer::get(json_decode(json_encode($schema), true), $pathItems);
        $lastSegment = substr($dataPointer, strrpos($dataPointer, '/') + 1);

        return in_array($lastSegment, $items, true);
 }
```

**Comment by vearutop** [comment]
@gigi please check [v0.12.9](https://github.com/swaggest/php-json-schema/releases/tag/v0.12.9). There is now `InvalidValue->getFailedSubSchema` method to resolve exception into `Schema` instance.

**Comment by jpwijbenga** [comment]
Comment about getFailedSubSchema

![image](https://user-images.githubusercontent.com/6123882/236933428-6410e085-8d15-4ab9-a97d-ebcf6067f01e.png)

Line 89 can override the schemapointer based on ref resolution, but line 98 does not use that value, calls the getter again? Is that correct?

**Comment by jpwijbenga** [comment]
Reason I'm asking is I'm looking for a way of getting a Sub-Schema from only 2 parts: root Schema object and DocumentPath string, specifically one that works with https $ref resolution.
