### ISSUE TITLE
Invalid date time format

### ISSUE THREAD

**Issue by RushOT** [swaggest/php-json-schema#83]
https://stackoverflow.com/questions/57658350/timezone-offset-format

**Comment by RushOT** [comment]
In the implementation package, date-time format which API is sending (`2019-08-26T12:32:42.503+0000`) is considered as `Invalid date-time format`. However, it is accepting `2019-08-26T12:32:42.503+00:00`. Is implementation wrong or API? How can avoid this mistake?

**Comment by RushOT** [comment]
`2019-08-26T12:32:42.503+00:00`

**Comment by RushOT** [comment]
In the implementation package, date-time format which API is sending (`2019-08-26T12:32:42.503+0000`) is considered as `Invalid date-time format`. However, it is accepting `2019-08-26T12:32:42.503+00:00`. Is implementation wrong or API? How can avoid this mistake?

**Comment by vearutop** [comment]
JSON Schema uses RFC3339 to define date-time format, 2019-08-26T12:32:42.503+0000 is not a valid RFC3339 representation so it does not qualify to pass JSON Schema validation as date-time.
