### ISSUE TITLE
Please add a CHANGELOG file

### ISSUE THREAD

**Issue by remicollet** [swaggest/php-json-schema#90]
Please, See https://keepachangelog.com/en/1.0.0/

**Comment by vearutop** [comment]
@remicollet thank you for this suggestion, could you expand on your particular need? 
Would you like it to be filled for past releases or is it enough to fill it from now on?

**Comment by remicollet** [comment]
> could you expand on your particular need?

This package is now in Fedora repository (need by some dep of phpMyAdmin), so change information have to be provide to end user on update

Ex: https://bodhi.fedoraproject.org/updates/FEDORA-2019-31eb2171f3


> fill it from now on would be enough for me

P.S. of course, same request for json-diff

**Comment by remicollet** [comment]
Thanks!
